CREATE TABLE IF NOT EXISTS notification_preferences (
  id SERIAL PRIMARY KEY,
  user_id TEXT NOT NULL UNIQUE,
  push_1h BOOLEAN NOT NULL DEFAULT TRUE,
  push_15min BOOLEAN NOT NULL DEFAULT TRUE,
  push_at_start BOOLEAN NOT NULL DEFAULT TRUE,
  email_24h BOOLEAN NOT NULL DEFAULT FALSE,
  email_1h BOOLEAN NOT NULL DEFAULT FALSE,
  email_15min BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
